export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAILUR = 'TASK_LIST_FAILUR'
export const TASK_LIST_DONE = 'TASK_LIST_DONE'