//tasks
export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAILUR = 'TASK_LIST_FAILUR'
export const TASK_LIST_DONE = 'TASK_LIST_DONE'

//create task
export const CREATE_TASK_REQUEST = 'TASK_LIST_REQUEST'
export const CREATE_TASK_SUCCESS = 'TASK_LIST_SUCCESS'
export const CREATE_TASK_FAILUR = 'TASK_LIST_FAILUR'
